### ISSUE TITLE
how to it in the monorepo project😢😢😢

### ISSUE THREAD

**Issue by CodeGetters** [ilearnio/module-alias#139]
I am a monorepo/packages/ used in the backend, project architecture is nestjs, I don't know how to use here.
Can someone tell me how to use it? Thank you very much!🥰

packages/back/package.json
```json
  "_moduleAliases": {
    "#": "dist"
  },
```
packages/back/src/app.ts
```ts
import { resolve } from "node:path";
import { init } from "module-alias";
init(resolve(__dirname, "../node_modules"));
import { AppModule } from "#/app.module";
```
error info
```txt
ERROR in ./src/main.ts 8:21-44
Module not found: Error: Can't resolve '#/app.module' in 'E:\software_cache\codetotal\vue\repo\vtiuse-full\packages\back\src'

webpack 5.89.0 compiled with 1 error in 2147 ms
E:\software_cache\codetotal\vue\repo\vtiuse-full\packages\back\dist\server.js:136
/******/                        throw e;
                                ^

TypeError: (0 , module_alias_1.init) is not a function
    at eval (webpack://@vtiuse-full/back/./src/main.ts?:5:25)      
    at ./src/main.ts (E:\software_cache\codetotal\vue\repo\vtiuse-full\packages\back\dist\server.js:19:1)
    at __webpack_require__ (E:\software_cache\codetotal\vue\repo\vtiuse-full\packages\back\dist\server.js:133:33)
    at E:\software_cache\codetotal\vue\repo\vtiuse-full\packages\back\dist\server.js:1059:37
    at Object.<anonymous> (E:\software_cache\codetotal\vue\repo\vtiuse-full\packages\back\dist\server.js:1061:12)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)  
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)      
    at Module._load (node:internal/modules/cjs/loader:938:12)      
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)

Node.js v20.9.0
```

**Comment by CodeGetters** [comment]
This problem has been solved, it seems to be the new version of nestjs webpack configuration file problem, just change the official website configuration file to the following content can be used normally
```js
// webpack-hmr.config.js
const nodeExternals = require("webpack-node-externals");
const { RunScriptWebpackPlugin } = require("run-script-webpack-plugin");

module.exports = function (options, webpack) {
  return {
    ...options,
    entry: ["webpack/hot/poll?100", options.entry],
    externals: [
      nodeExternals({
        allowlist: ["webpack/hot/poll?100"],
      }),
    ],
    plugins: [
      ...options.plugins,
      new webpack.HotModuleReplacementPlugin(),
      new webpack.WatchIgnorePlugin({
        paths: [/\.js$/, /\.d\.ts$/],
      }),
      new RunScriptWebpackPlugin({
        name: options.output.filename,
        autoRestart: false,
      }),
    ],
  };
};
```
Script command changed to `nest build --webpack --webpackPath webpack-hmr.config.js --watch`
